### ISSUE TITLE
Enable visualisation of data + fits in different voxels

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/qMTLab#10]
Using impixel

**Comment by jfcabana** [comment]
I don't understand what that means... Explain?

**Comment by halfSpinDoctor** [comment]
​I think it is in reference to this MATLAB feature:
http://uk.mathworks.com/help/images/ref/impixel.html

Sam​

**Comment by tanguyduval** [comment]
Sorry I wasn't clear..  
The idea is to be able to plot the data points in a voxel selected by the user (using impixel). Plot SPGRs as a function of the offset frequency. Plot IRFSE as a function of the Inversion Time TI ... 

Even better would be to assess visually the quality of the fitting in a voxel selected by the user. So same plot as above, with fitting curve result plotted on top of experimental data.

**Comment by jfcabana** [comment]
Ah yes, I see. I had that in mind too. Will work on that soon.

**Comment by jfcabana** [comment]
Done. Added a button 'View data fit' that will pop a new figure showing the raw data + fitted curve of the currently selected voxel (first click on 'Select' in Cursor mode section to be able to select voxels)

**Comment by tanguyduval** [comment]
Great functionnality, however there is an error if user hasn't done the fitting before:
`````
Attempt to reference field of non-structure array.

Error in qMTLab>ViewDataFit_Callback (line 1305)
S = size(FitResults.F);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in qMTLab (line 31)
    gui_mainfcn(gui_State, varargin{:});

Error in @(hObject,eventdata)qMTLab('ViewDataFit_Callback',hObject,eventdata,guidata(hObject))
`````

A nice approch would be to call FitData (using data of the selected pixel), and not Fitting results. It will allow user to test different options without having to fit all voxels each time.

**Comment by jfcabana** [comment]
Good idea. I will look into that.

**Comment by jfcabana** [comment]
Done. Thanks for the suggestion, this is a great feature!

**Comment by tanguyduval** [comment]
Great! I did some small modif. pull qMTLab.m to prevent conflicts

**Comment by jfcabana** [comment]
Nice job. I love it :)

**Comment by jfcabana** [comment]
Tanguy, it might be a good idea to make it so that if you select a different voxel to plot then it opens in a new figure, but if it's the same voxel with new fit options then it's in the same figure?

**Comment by tanguyduval** [comment]
I did that to (i) prevent the opening of too many figures and (ii) compare two voxels at different locations. If user wants a clean plot, he can close the figure.
It's just a personal preference, the other way is good also..
