### ISSUE TITLE
Fitting crashed at first iter because of corrupted Sf Table 

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/qMTLab#14]
Build Sf Table button completes successfully but creates non monotically increasing angles using SPGR example dataset.
Produce an error at 1st iter of Fit Data:
````
Error using griddedInterpolant
The grid vectors are not strictly monotonic increasing.

Error in interp3 (line 130)
        F = griddedInterpolant({X, Y, Z}, V, method,extrap);

Error in GetSf (line 9)
Sfi(ii) = interp3(SfTable.offsets, SfTable.angles, SfTable.T2f, SfTable.values, xi, yi, zi);

Error in SPGR_Srp_fun (line 46)
Sf = GetSf(Angles,Offsets,T2f,Prot.Sf);
````

Indeed the issue is:
SfTable.angles  =
           0
         300
         400
         500
         600
         800
        **1000**
         **900**
        1200
        1500
        1800

Here is the protocol:
![image](https://cloud.githubusercontent.com/assets/7785316/14511662/27b5e87c-01a7-11e6-99b3-b8b1ed3f558b.png)

**Comment by jfcabana** [comment]
Thanks for finding that out! Fixed now.
