### ISSUE TITLE
Bugs in Viewer

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/qMTLab#2]
1- initial viewing slice is 16 --> bug when less that 16slices
2- initial colormap is "min"/"max"--> non numeric --> crash

**Comment by jfcabana** [comment]
HI Tanguy, thank you for testing the software. Could you provide more details about the situation in which you encountered a bug, as I was unable to reproduce them. 

1. When you load a fit file or when a fitting procedure is completed, the initial slice should be set to the mid point in the volume. e.g. for a 32 slices volume the initial view would be slice 16, for a 64 slices it would be 32.

2. "min" and "max" are displayed only as a field name before any data is plotted. When some data is displayed for the first time, the values should be changed automatically to the min and max values of the current map.

**Comment by tanguyduval** [comment]
Hello JF,

So my data have 3 slices and initial slice isn't modified by default.
Please find my data here: https://drive.google.com/folderview?id=0B2Xe6kvfjHHnZDlQQ1FyMGU3U0U&usp=sharing

Best,
Tanguy

**Comment by tanguyduval** [comment]
Also I would like to push some modifications on a new branch (e.g. "Tanguy"). Could you give me access??

**Comment by jcohenadad** [comment]
i just added you in the team

--
Julien Cohen-Adad, PhD
Assistant Professor, Polytechnique Montreal
Associate Director, Functional Neuroimaging Unit, University of Montreal
Phone: 514 340 5121 (office: 2264);  Skype: jcohenadad
Web: www.neuro.polymtl.ca

**Comment by tanguyduval** [comment]
Ok thanks

**Comment by jfcabana** [comment]
Hello Tanguy,
I fixed the bugs in the viewer. I tried it with your data and it's working fine now.
Thank you for signaling the problem!
JF

**Comment by tanguyduval** [comment]
Thanks!
