### ISSUE TITLE
Urgent Bug: R1f parameter fixed by default in SPGR fitting options upon startup

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/qMTLab#23]
Conventionally, R1r is fixed to a value of 1. I noticed yesterday while debugging an issue of a new user that R1f is also being fixed by default (see red circle in screenshot below), even though the option of using R1maps is also checked. Using this configuration will lead to severe errors in the F and kf fitted parameters, as R1f, R1map, F and kf are all related through equation 7 of Sled's 2001 paper.

If R1maps are used, I can't think of a situation where R1f should be fixed, however particularly not as the default option of the software. R1maps are used to constrain R1f, so that F and kf fit better.

![qmtlab_bug](https://cloud.githubusercontent.com/assets/1421029/22705847/b174022e-ed47-11e6-9972-01aa987a9a87.png)

I'm not very familiar with editing Matlab GUIs, however I'm fairly certain this would be an easy fix, and would make it more user-friendly for new users trying to fit their first protocols.

**Comment by jfcabana** [comment]
You're quite right, this default option doesn't make a lot of sense. I fixed it already. It only involves changing the "DefaultFitOpt.mat" file in the SPGR dir.

**Comment by mathieuboudreau** [comment]
Thanks a lot!
