### ISSUE TITLE
qMTLab calls startup.m on opening --> conflicts

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/qMTLab#9]
1- startup.m is a matlab function.. change the name to qMTstartup.m . Can produce crashes
2- Would be great to be able to work in a different folder than qMTLab. Currently if users changes the Matlab folder while qMTLab is running it creates a bug as soon as he click on a button

**Comment by jfcabana** [comment]
Thanks for the report Tanguy. I will change startup.m as soon as my current fitting is done.

As for #2, I'm aware of that, and I already tried to fix this, but this will require some work as for now qMTLab relies heavily on the current directory architecture to set things up depending on your chosen qMT method.

Anyway, I'll get to it when I have a moment.

Also, would you be interested in being a contributor to the repo? Maybe you could ask Julien to make you an admin so you can readily fix some bugs when you spot them?

**Comment by tanguyduval** [comment]
Hey JF,

You are still very active on qMTLab! 
I created my own branch. I just solved the first part of this issue in my branch. I will merge it after testing.

**Comment by jfcabana** [comment]
Yes, I'm trying to do a little push to get the software ready to present at ISMRM!
Good to know that you are contributing as well.
